### ISSUE TITLE
Question about seed

### ISSUE THREAD

**Issue by zengkaiwei** [yxgeee/MMT#1]
sh scripts/pretrain.sh dukemtmc msmt17 resnet50 1
sh scripts/pretrain.sh dukemtmc msmt17 resnet50 2
1 和2 代表的似乎是seed？意思是在sourcetrain的时候就生成了两个不同的模型吗，我看论文的理解是在第二步MMT中为了coteaching 才会有两个不同的网络

**Comment by yxgeee** [comment]
你好，是表示不同的seed，给两个网络用不同的seed进行source-domain pretrain，增强互补性。

实现说明参见论文4.2.2 Stage 1: “Given the mini-batch of images, network parameters θ1, θ2 are updated **independently**”
