### ISSUE TITLE
Question For MSMT17

### ISSUE THREAD

**Issue by WangWenhao0716** [yxgeee/MMT#10]
I want to use MSMT17 dataset, however, I cannot find "'list_train.txt'", 'list_val.txt', 'list_query.txt', 'list_gallery.txt'. Maybe there is something wrong about my download. How can I fix the problem?

**Comment by yxgeee** [comment]
We use MSMT17_V1 dataset. Please download MSMT17_V1 instead of MSMT17_V2.

**Comment by WangWenhao0716** [comment]
Sorry, after I download MSMT17_V1 dataset. I still cannot find the 4 txt files. Can you send them to wangwenhao@buaa.edu.cn?

**Comment by White1973** [comment]
When I download MSMT17_V1 dataset, I also cannot find the 4 txt files, could send them to whitesk19@mail.nwpu.edu.cn?

**Comment by hjwang-824** [comment]
I also cannot find the txt files， would you please send them to haijianwang@163.com？

**Comment by keenJMS** [comment]
> Sorry, after I download MSMT17_V1 dataset. I still cannot find the 4 txt files. Can you send them to [wangwenhao@buaa.edu.cn](mailto:wangwenhao@buaa.edu.cn)?

Did you get these txts?  would you please send them to 656800758@qq.com？

**Comment by WangWenhao0716** [comment]
Sorry. To protect the privacy, you should download it by sending an email to its owner. Thanks



发自我的&nbsp;iPad


------------------ Original ------------------

**Comment by yxgeee** [comment]
To all,

The list files for MSMT17 can be found at https://drive.google.com/drive/folders/11kyHCCYg3aCi7hEVzH1iaxxY3G-_PpUG?usp=sharing. As for the raw images, please send an email to the owner of the dataset for request. And note that in my experiments, I used MSMT17_V1, where faces are not masked.

Best

**Comment by sakura811** [comment]
> To all,
> 
> The list files for MSMT17 can be found at https://drive.google.com/drive/folders/11kyHCCYg3aCi7hEVzH1iaxxY3G-_PpUG?usp=sharing. As for the raw images, please send an email to the owner of the dataset for request. And note that in my experiments, I used MSMT17_V1, where faces are not masked.
> 
> Best

Sorry to distrub. I found a msmt17 dataset in your https://drive.google.com/drive/folders/11I7p0Dr-TCC9TnvY8rWp0B47gCB3K0T4, I also have this same dataset with yours, it seemed that the faces are not masked, but the list files which you shared not correspond with this dataset. So I am not sure it is the MSMT17_V1, or MSMT_V2. 
Thank you very much.

**Comment by yxgeee** [comment]
> > To all,
> > The list files for MSMT17 can be found at https://drive.google.com/drive/folders/11kyHCCYg3aCi7hEVzH1iaxxY3G-_PpUG?usp=sharing. As for the raw images, please send an email to the owner of the dataset for request. And note that in my experiments, I used MSMT17_V1, where faces are not masked.
> > Best
> 
> Sorry to distrub. I found a msmt17 dataset in your https://drive.google.com/drive/folders/11I7p0Dr-TCC9TnvY8rWp0B47gCB3K0T4, I also have this same dataset with yours, it seemed that the faces are not masked, but the list files which you shared not correspond with this dataset. So I am not sure it is the MSMT17_V1, or MSMT_V2.
> Thank you very much.

The link you shared is not owned by me. So I am not sure whether it is V1.

**Comment by edwardnguyen1705** [comment]
@WangWenhao0716 
Could you tell me where you got MSMT17_v1?
Thank you.

**Comment by WangWenhao0716** [comment]
I get it from my tutor.&nbsp;



发自我的&nbsp;iPad


------------------ Original ------------------
From: Thanh Nguyen ***@***.***&gt;
Date: Wed,Sep 1,2021 0:52 AM
To: yxgeee/MMT ***@***.***&gt;
Cc: Wenhao Wang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [yxgeee/MMT] Question For MSMT17 (#10)





 
@WangWenhao0716
 Could you tell me where you got MSMT17_v1?
 Thank you.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
