### ISSUE TITLE
One question about Euclidean computation

### ISSUE THREAD

**Issue by hezhping** [yxgeee/MMT#12]
There are two lines code in function _**compute_jaccard_dist**_
original_dist = torch.pow(target_features, 2).sum(dim=1, keepdim=True) * 2
original_dist = original_dist.expand(N, N) - 2 * torch.mm(target_features, target_features.t())
I think it should be:
original_dist = torch.pow(target_features, 2).sum(dim=1, keepdim=True) 
original_dist = original_dist.expand(N, N) + original_dist.t().expand(N,N) - 2 * torch.mm(target_features, target_features.t())

**Comment by yxgeee** [comment]
Hi, you’re right. But the results are actually the same, because the features are normalized.

**Comment by yxgeee** [comment]
I will revise it for better understanding. Thanks!

**Comment by hezhping** [comment]
> Hi, you’re right. But the results are actually the same, because the features are normalized.

Yep, thank you for your reply, I am trying your code recently, its results really impressed me. Thank you.

**Comment by yxgeee** [comment]
Hi,
This issue has been fixed in [OpenUnReID/core/utils/compute_dist.py](https://github.com/open-mmlab/OpenUnReID/blob/master/openunreid/core/utils/compute_dist.py#L146), and welcome to use our refactored code!
