### ISSUE TITLE
SoftTripletLoss margin

### ISSUE THREAD

**Issue by pmorerio** [yxgeee/MMT#13]
Hi, 
first of all thanks for sharing such great code.
Can I ask you the meaning of setting `margin=0.0` versus `margin=None` in the `MMTTrainer`?
Inspecting the `SoftTripletLoss` class looks like `margin=None` implements equation 8 in the paper, while setting the margin to any float would boil it down to equation 6. Am I correct?
Thank you very much.

https://github.com/yxgeee/MMT/blob/aeb547079c65d9aa2b8ce08d587970412d362b07/mmt/trainers.py#L172
https://github.com/yxgeee/MMT/blob/aeb547079c65d9aa2b8ce08d587970412d362b07/mmt/trainers.py#L173

**Comment by yxgeee** [comment]
Hi, your understanding is exactly right.
When setting the margin to a float number like **0.0**, _(1-margin)_ becomes the hard label in equation 6, e.g. **1** in our paper.

**Comment by yxgeee** [comment]
Hi, your understanding is exactly right.
When setting the margin to a float number like **0.0**, (1-margin) becomes the label in equation 6, e.g. **1** in our paper.

**Comment by pmorerio** [comment]
Thank you very much!
