### ISSUE TITLE
How to include more dataset ?

### ISSUE THREAD

**Issue by absagargupta** [yxgeee/MMT#19]
I am currently working and have got results on Sysu Dataset(through some other algorithm). What changes do I make in the code so as to run this on Sysu. I have made Sysu.py just like dukemtmc.py and placed the dataset at the same place as other dataset. I have also included it in __init__.py (__factory) of the datasets folder. Whenever I try running the sh scripts/pretrain.sh Sysu market1501 resnet50 1 it show the error that only defaults datasets "dukemtmc", "msmt", market1501 can be used.

**Comment by yxgeee** [comment]
Did you run `python setup.py —install` after changing the code?

**Comment by yxgeee** [comment]
Did you run `python setup.py install` after changing the code?

**Comment by absagargupta** [comment]
Ohh. Thank you. I forgot to run it again. So any changes I make in the original code I have to do that python setup.py install. Got it :-)
