### ISSUE TITLE
MSMT17_1V

### ISSUE THREAD

**Issue by yjh576** [yxgeee/MMT#22]
Hi, I can't download the MSMT17_V1 dataset. Can you send it to me? If necessary, I can sign some agreements. Thank you!

**Comment by yxgeee** [comment]
Hi, you'd better directly contact with the first author Longhui Wei (longhuiwei@pku.edu.cn) of MSMT17 dataset(https://arxiv.org/pdf/1711.08565.pdf). I think he will be glad to share it with you.

**Comment by yjh576** [comment]
Thank you. You are very kind.
