### ISSUE TITLE
a question on the vesion of MSMT17 dataset

### ISSUE THREAD

**Issue by zkcys001** [yxgeee/MMT#24]
Hi,
Thx for the good code. 
I have a question，does the performance of the MSMT17_v1 dataset differ from that of the MSMT17_v2 dataset?

**Comment by yxgeee** [comment]
Hi,
I did not try the MSMT17_v2 dataset. As I know, MSMT17_V2 adds masks to blur people's faces based on MSMT17_V1, however, person re-ID models generally distinguish different people with their clothes. So I guess the performance won't have a large difference.
