### ISSUE TITLE
MSMT17 datasets

### ISSUE THREAD

**Issue by zongzhesun** [yxgeee/MMT#3]
Thanks for your great work!
But I failed to download the MSMT17 dataset from the link: http://www.pkuvmc.com/dataset.html.
Could you provide me the resource for the MSMT17 dataset? It'll only be used for academic purposes.
My email is 973507183@qq.com.
Thank you!

**Comment by yxgeee** [comment]
I have sent the link by email. Please kindly check.

**Comment by zongzhesun** [comment]
I have received your letter. Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yixiao Ge"<notifications@github.com&gt;; 
发送时间: 2020年1月13日(星期一) 下午4:02
收件人: "yxgeee/MMT"<MMT@noreply.github.com&gt;; 
抄送: "zongzhe_sun"<973507183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yxgeee/MMT] MSMT17 datasets (#3)




I have sent the link by email. Please kindly check.
