### ISSUE TITLE
No module named 'mmt'

### ISSUE THREAD

**Issue by zhanghongruiupup** [yxgeee/MMT#31]
sh scripts/pretrain.sh dukemtmc market1501 resnet50 1
info:No module named 'mmt'
thanks your code,hope your reply

**Comment by yxgeee** [comment]
Have you done `python setup.py install` in https://github.com/yxgeee/MMT#installation?

**Comment by zhanghongruiupup** [comment]
> Have you done `python setup.py install` in https://github.com/yxgeee/MMT#installation?

Downloading, it's too slow
