### ISSUE TITLE
an error in evaluator

### ISSUE THREAD

**Issue by saga4me** [yxgeee/MMT#37]
你好作者 在目录mmt的feature_extraction文件夹下的cnn.py文件,定义了一个extraction_cnn_feature函数 outputs＝model（inputs）  outputs包含了.data属性与.values属性 我在用其他backbone替换resnet时候会在evaluate时候报错 错误就是我的outputs没有这两个属性 
请问作者 outputs.data 与outputs.values 这两个属性是在哪里定义的 我没有找到
辛苦作者回答一下 十分感谢

**Comment by yxgeee** [comment]
`.data` 就是pytorch的tensor放在cuda上的时候，就会自带这个属性。`.values`的话code里用不上，每次从14行就退出去了。

**Comment by GuaPiQ** [comment]
作者您好，我复现了您的代码，在用kmeans 、resnet50、dukeTomarket的情况下mAP达到了68.7%，top1达到85.8%。但是和您论w文中的准确性mAP=71.2%, top1=87.7%还差一点。我用了一个GPU，batchsize=16。想问问您是因为batchsize的原因吗。
