### ISSUE TITLE
About sampler

### ISSUE THREAD

**Issue by signofyouth** [yxgeee/MMT#38]
Thank you for your great work. I'm very interested in your paper.<br>
When trying your code, I found RandomMultipleGallerySampler sometimes gives an ID which contains only 1 instance in a batch.
This is because 1 instance pushed in 'ret' at line 74 was remained even when continued at https://github.com/yxgeee/MMT/blob/master/mmt/utils/data/sampler.py#L93.<br>
Would you check and fix it? Thank you.

**Comment by yxgeee** [comment]
Yes, but it is not a bug here. Does it cause any running issues in your experiments?

**Comment by signofyouth** [comment]
Thank you for your quick reply.<br>
No, errors does not occur when running on your code. And the result does not change as far as I tried.
However, it's a little uncomfortable that the sampling policy(4 instances per ID) would not always work.

Anyway, you're right it is not a bug here. Please close this issue.
