### ISSUE TITLE
About experimental result

### ISSUE THREAD

**Issue by GuaPiQ** [yxgeee/MMT#39]
作者您好，我复现了您的代码，在用kmeans 、resnet50、dukeTomarket的情况下mAP达到了68.7%，top1达到85.8%。但是和您论w文中的准确性mAP=71.2%, top1=87.7%还差一点。我用了一个GPU，batchsize=16。想问问您是因为batchsize的原因吗。

**Comment by yxgeee** [comment]
应该是的，batchsize和GPU数量会有影响

**Comment by GuaPiQ** [comment]
哦哦，好的，谢谢您。
